"""P3.5-01: Explainability router for LLM streaming."""
from fastapi import APIRouter, Request
from sse_starlette.sse import EventSourceResponse

from app.schemas.explain import ExplainRequest
from app.services.explain import generate_explanation_stream

router = APIRouter(tags=["LLM Explainability"])


@router.post("/", summary="Stream AI explanation of prediction")
async def explain_prediction(
    request: Request,
    payload: ExplainRequest,
):
    """
    Takes the extracted acoustic features and the ensemble prediction probability,
    and returns a streaming Server-Sent Events (SSE) response containing a 
    plain-English explanation generated by the LLM.
    """
    # Use EventSourceResponse to handle the SSE streaming wrapper over the AsyncGenerator
    return EventSourceResponse(
        generate_explanation_stream(payload),
        media_type="text/event-stream",
    )
