import { Document, Page, Text, View, pdf } from "@react-pdf/renderer";
import type { PredictionResponse, ShapContribution } from "../../api/client";
import { COLORS, reportStyles as s } from "./styles";

interface ReportProps {
  prediction: PredictionResponse;
  features: Record<string, number>;
  /** Optional preformatted narrative paragraph from the LLM narrator. */
  narrative?: string | null | undefined;
  /** Document title shown in PDF metadata. */
  title?: string | undefined;
}

function riskBand(prob: number): { label: string; style: { color: string } } {
  if (prob >= 0.7) return { label: "High Risk", style: s.riskHigh };
  if (prob >= 0.4) return { label: "Borderline", style: s.riskMid };
  return { label: "Low Risk", style: s.riskLow };
}

function barColor(prob: number): string {
  if (prob >= 0.7) return COLORS.destructive;
  if (prob >= 0.4) return COLORS.warning;
  return COLORS.success;
}

function ShapBar({ contribution, maxAbs }: { contribution: ShapContribution; maxAbs: number }) {
  const positive = contribution.shap >= 0;
  const pct = (Math.abs(contribution.shap) / Math.max(maxAbs, 1e-9)) * 100;
  return (
    <View style={s.shapRow}>
      <Text style={s.shapFeature}>{contribution.feature}</Text>
      <View style={s.shapBarWrap}>
        <View style={s.shapBarLeft}>
          {!positive && (
            <View
              style={[s.shapBarFill, { width: `${pct}%`, backgroundColor: COLORS.success }]}
            />
          )}
        </View>
        <View style={s.shapAxis} />
        <View style={s.shapBarRight}>
          {positive && (
            <View
              style={[s.shapBarFill, { width: `${pct}%`, backgroundColor: COLORS.destructive }]}
            />
          )}
        </View>
      </View>
      <Text
        style={[s.shapValue, { color: positive ? COLORS.destructive : COLORS.success }]}
      >
        {positive ? "+" : ""}
        {contribution.shap.toFixed(2)}
      </Text>
    </View>
  );
}

export function ReportDocument({ prediction, features, narrative, title }: ReportProps) {
  const risk = riskBand(prediction.ensemble.probability);
  const probPct = (prediction.ensemble.probability * 100).toFixed(1);
  const created = new Date(prediction.created_at);
  const shapTop = (prediction.ensemble.shap_top ?? []).slice().sort(
    (a, b) => Math.abs(b.shap) - Math.abs(a.shap),
  );
  const maxAbs = Math.max(...shapTop.map((c) => Math.abs(c.shap)), 1e-9);
  const featureEntries = Object.entries(features).sort(([a], [b]) => a.localeCompare(b));

  return (
    <Document title={title ?? "Parkinson's Voice Detection Report"}>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <View>
            <Text style={s.brand}>Parkinson's Voice Detection</Text>
            <Text style={s.brandSub}>Acoustic feature analysis report</Text>
          </View>
          <View style={s.metaBlock}>
            <Text style={s.metaLine}>Generated: {created.toLocaleString()}</Text>
            <Text style={s.metaLine}>Prediction ID: {prediction.prediction_id || "—"}</Text>
            <Text style={s.metaLine}>Input mode: {prediction.input_mode}</Text>
          </View>
        </View>

        <View style={s.disclaimerCard}>
          <Text style={s.disclaimerTitle}>Important — Research Use Only</Text>
          <Text style={s.disclaimerText}>
            {prediction.disclaimer ||
              "This report is generated by a machine-learning model trained on a small public dataset (UCI Parkinson's, n=195). It is NOT a medical diagnosis. Do not use this output to make health decisions. Consult a qualified neurologist for clinical assessment."}
          </Text>
        </View>

        <View>
          <Text style={s.sectionTitle}>Result Summary</Text>
          <View style={s.summaryCard}>
            <Text style={[s.summaryProb, risk.style]}>{probPct}%</Text>
            <View style={s.summaryMeta}>
              <Text style={[s.summaryLabel, risk.style]}>{risk.label}</Text>
              <Text style={s.summaryDesc}>
                Ensemble probability of Parkinson's disease across {prediction.per_model.length} classifiers.
                Primary model: {prediction.primary_model.replace(/_/g, " ")}.
              </Text>
            </View>
          </View>
        </View>

        {narrative && narrative.trim().length > 0 && (
          <View style={{ marginBottom: 14 }}>
            <Text style={s.sectionTitle}>AI Narrative</Text>
            <Text style={{ fontSize: 9, color: COLORS.text, lineHeight: 1.5 }}>{narrative}</Text>
          </View>
        )}

        <View style={{ marginBottom: 14 }}>
          <Text style={s.sectionTitle}>Per-Model Breakdown</Text>
          {prediction.per_model.map((m) => {
            const pct = (m.probability * 100).toFixed(0);
            return (
              <View key={m.model_name} style={s.modelRow}>
                <Text style={s.modelName}>{m.model_name.replace(/_/g, " ")}</Text>
                <View style={s.modelBarTrack}>
                  <View
                    style={[
                      s.modelBarFill,
                      { width: `${m.probability * 100}%`, backgroundColor: barColor(m.probability) },
                    ]}
                  />
                </View>
                <Text style={[s.modelProb, { color: barColor(m.probability) }]}>{pct}%</Text>
              </View>
            );
          })}
        </View>

        {shapTop.length > 0 && (
          <View style={{ marginBottom: 14 }} wrap={false}>
            <Text style={s.sectionTitle}>Top Feature Contributions (SHAP)</Text>
            {shapTop.slice(0, 8).map((c) => (
              <ShapBar key={c.feature} contribution={c} maxAbs={maxAbs} />
            ))}
          </View>
        )}

        <View>
          <Text style={s.sectionTitle}>Feature Snapshot</Text>
          <View style={s.featureGrid}>
            {featureEntries.map(([name, value]) => (
              <View key={name} style={s.featureCell}>
                <Text style={s.featureName}>{name}</Text>
                <Text style={s.featureValue}>
                  {Number.isFinite(value) ? Number(value).toFixed(5) : "—"}
                </Text>
              </View>
            ))}
          </View>
        </View>

        <View style={s.footer} fixed>
          <Text>Parkinson's Voice Detection — Research Use Only</Text>
          <Text
            render={({ pageNumber, totalPages }) => `Page ${pageNumber} / ${totalPages}`}
          />
        </View>
      </Page>
    </Document>
  );
}

/**
 * Render and trigger a download of the PDF report. Returns the generated Blob
 * so callers can also open it in a new tab if desired.
 */
export async function downloadReport(props: ReportProps, filename = "parkinsons-report.pdf"): Promise<Blob> {
  const blob = await pdf(<ReportDocument {...props} />).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  // Revoke after a tick so the download has time to start.
  setTimeout(() => URL.revokeObjectURL(url), 1500);
  return blob;
}
